### ISSUE TITLE
Redesign Database Schema

### ISSUE THREAD

**Issue by ssiannas** [SpyrosSiannas/record-label-webapp#38]
Issue Description
---
We need to update the DBDesigner Schema based on the new ERD
![image](https://user-images.githubusercontent.com/59615151/118722449-d5389f00-b834-11eb-94db-c15020067d60.png)

**Comment by ssiannas** [comment]
@arslanoglou do not forget to add `Event <- Performs -> Artist`

**Comment by arslanoglou** [comment]
- [x]  Added "Event" Entity
- [x]  Redesigned Schema on DBDesigner (find it [here](https://app.dbdesigner.net/designer/schema/412094))

**Comment by arslanoglou** [comment]
- [x]  Added "Cheatsheet" attribute to Artist
- [x]  Added "Profession" attribute to Artist
- [x]  Redesigned database on DB Designer

New Schema
![New](https://user-images.githubusercontent.com/62408856/119273832-69c84600-bc15-11eb-88ad-c8dc729d39a1.jpg)



Example on artist's page ![here](https://user-images.githubusercontent.com/62408856/119259784-8f832a00-bbd8-11eb-8d53-670d8f363fc0.png)

#
You can download the new schema [here](https://github.com/SpyrosSiannas/record-label-webapp/files/6528779/diagram.6.zip)

**Comment by ssiannas** [comment]
@arslanoglou the variable types for many fields need changing. We should change every primary key to an integer since it's an identifier and change all the relevant fields to the respective variable type

**Comment by ssiannas** [comment]
@arslanoglou We need seperate tables for the N:N relationships. Namely the `References` and `Performs` ones, just like with the `Places` table.
