### ISSUE TITLE
Gather data for the database

### ISSUE THREAD

**Issue by ssiannas** [SpyrosSiannas/record-label-webapp#47]
Issue Description
---
Based on #38 we should create csv files with all our database info ready to be loaded.

**Comment by arslanoglou** [comment]
CSV, img and txt files : [Uploading Artists_data.zip…]()

**Comment by arslanoglou** [comment]
[CSV, img and txt files ](https://github.com/SpyrosSiannas/record-label-webapp/files/6587782/Artists_data.zip)
